# .github/workflows/fly.deploy.yml
name: Fly Deploy
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      FLY_APP: sdv-bot
      FLY_REGION: iad

    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Ensure Fly volume exists
        run: |
          flyctl volumes create data \
            --app "$FLY_APP" \
            --region "$FLY_REGION" \
            --size 1 || true

      - name: Deploy
        run: |
          flyctl deploy \
            --app "$FLY_APP" \
            --remote-only \
            --dockerfile Dockerfile \
            --strategy immediate
